## Laboratorio
Limpiar un set de datos con pandas

● Un set de datos que tengan permisos para compartir con nosotros

○ Más de 100000 registros

○ Más de 20 columnas

○ Con datos con cadenas, números, fechas, y categorías

● Usar los permisos de edificación de San Francisco
https://www.kaggle.com/aparnashastry/building-permit-applications-data/data
El análisis tiene que ser reproducible en las máquinas de los profes

In [1]:
import pandas as pd
import numpy as np
np.random.seed(0)

In [2]:
import chardet
# look at the first ten thousand bytes to guess the character encoding
with open("Building_Permits.csv", 'rb') as rawdata:
    result = chardet.detect(rawdata.read(1000000))

# check what the character encoding might be
print(result)

{'confidence': 1.0, 'language': '', 'encoding': 'ascii'}

In [3]:
#Al leer el archivo con encoding ascii obtenemos un error 'ascii' codec can't decode byte 0xe2 in position 66: ordinal not in range(128)

databuild = pd.read_csv("Building_Permits.csv", encoding='ascii')

databuild.head()

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 66: ordinal not in range(128)

In [4]:
# Leemos el archivo con codificación utf-8
databuild = pd.read_csv("Building_Permits.csv", encoding='utf-8')


databuild.head()

C:\Users\HP\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992

In [5]:
databuild.sample(5,random_state=2)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
136427,201609127434,8,otc alterations permit,09/12/2016,2036B,013,580,NaN,Ortega,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,7.0,Inner Sunset,94122.0,"(37.75487502148424, -122.46968263494958)",1437040122900
133645,201608165127,8,otc alterations permit,08/16/2016,3777,002,508,NaN,04th,St,...,2.0,constr type 2,2.0,constr type 2,NaN,6.0,South of Market,94107.0,"(37.77919302122572, -122.39809470909802)",1433853167388
135728,201609066867,8,otc alterations permit,09/06/2016,1738,016,1275,NaN,12th,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,5.0,Inner Sunset,94122.0,"(37.76430230651868, -122.4698806944239)",1436258112300
104372,201511021454,8,otc alterations permit,11/02/2015,1762,043,649,NaN,Irving,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,5.0,Inner Sunset,94122.0,"(37.763847035476005, -122.4650594546687)",1401620462462
8135,201303283275,8,otc alterations permit,03/28/2013,6192,051,367,NaN,Wilde,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,10.0,Visitacion Valley,94134.0,"(37.71669786269351, -122.40419981098455)",1300118197915

In [6]:
#Quitamos los espacios en los nombres de las columnas
databuild.columns[databuild.columns != databuild.columns.str.extract(r'^(\w+)$')]

C:\Users\HP\Anaconda\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  from ipykernel import kernelapp as app

Index(['Permit Number', 'Permit Type', 'Permit Type Definition',
       'Permit Creation Date', 'Street Number', 'Street Number Suffix',
       'Street Name', 'Street Suffix', 'Unit Suffix', 'Current Status',
       'Current Status Date', 'Filed Date', 'Issued Date', 'Completed Date',
       'First Construction Document Date', 'Structural Notification',
       'Number of Existing Stories', 'Number of Proposed Stories',
       'Voluntary Soft-Story Retrofit', 'Fire Only Permit',
       'Permit Expiration Date', 'Estimated Cost', 'Revised Cost',
       'Existing Use', 'Existing Units', 'Proposed Use', 'Proposed Units',
       'TIDF Compliance', 'Existing Construction Type',
       'Existing Construction Type Description', 'Proposed Construction Type',
       'Proposed Construction Type Description', 'Site Permit',
       'Supervisor District', 'Neighborhoods - Analysis Boundaries',
       'Record ID'],
      dtype='object')

In [7]:
#Reemplazamos los espacios en los nombres de las columnas por "_"
databuild.columns = databuild.columns.str.replace(' ', '_')
databuild.head()

,Permit_Number,Permit_Type,Permit_Type_Definition,Permit_Creation_Date,Block,Lot,Street_Number,Street_Number_Suffix,Street_Name,Street_Suffix,...,Existing_Construction_Type,Existing_Construction_Type_Description,Proposed_Construction_Type,Proposed_Construction_Type_Description,Site_Permit,Supervisor_District,Neighborhoods_-_Analysis_Boundaries,Zipcode,Location,Record_ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992

In [8]:
#Verificamos otra vez las columnas que siguen teniendo caracteres raros
databuild.columns[databuild.columns != databuild.columns.str.extract(r'^(\w+)$')]

C:\Users\HP\Anaconda\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  from ipykernel import kernelapp as app

Index(['Voluntary_Soft-Story_Retrofit', 'Neighborhoods_-_Analysis_Boundaries'], dtype='object')

In [9]:
# Vamos a arreglar los dos nombres de columnas restantes

databuild=databuild.rename(columns = {"Neighborhoods_-_Analysis_Boundaries":"Neighborhoods_Analysis_Boundaries",
                           "Voluntary_Soft-Story_Retrofit":"Voluntary_Soft_Story_Retrofit"})

In [10]:
#Comprobamos una última vez
databuild.columns[databuild.columns != databuild.columns.str.extract(r'^(\w+)$')]

C:\Users\HP\Anaconda\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  from ipykernel import kernelapp as app

Index([], dtype='object')

In [11]:
databuild.describe()

C:\Users\HP\Anaconda\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

,Permit_Type,Street_Number,Unit,Number_of_Existing_Stories,Number_of_Proposed_Stories,Estimated_Cost,Revised_Cost,Existing_Units,Proposed_Units,Plansets,Existing_Construction_Type,Proposed_Construction_Type,Supervisor_District,Zipcode,Record_ID
count,198900.000000,198900.000000,29479.000000,156116.000000,156032.000000,1.608340e+05,1.928340e+05,147362.000000,147989.000000,161591.000000,155534.000000,155738.000000,197183.000000,197184.000000,1.989000e+05
mean,7.522323,1121.728944,78.517182,5.705773,5.745043,1.689554e+05,1.328562e+05,15.666164,16.510950,1.274650,4.072878,4.089529,5.538403,94115.500558,1.162048e+12
std,1.457451,1135.768948,326.981324,8.613455,8.613284,3.630386e+06,3.584903e+06,74.476321,75.220444,22.407345,1.585756,1.578766,2.887041,9.270131,4.918215e+11
min,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,94102.000000,1.293532e+10
25%,8.000000,235.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.308567e+12
50%,8.000000,710.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.371840e+12
75%,8.000000,1700.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.435000e+12
max,8.000000,8400.000000,6004.000000,78.000000,78.000000,5.379586e+08,7.805000e+08,1907.000000,1911.000000,9000.000000,5.000000,5.000000,11.000000,94158.000000,1.498342e+12

In [12]:
#Verificamos los tipos de datos de cada columna
databuild.dtypes

Permit_Number                              object
Permit_Type                                 int64
Permit_Type_Definition                     object
Permit_Creation_Date                       object
Block                                      object
Lot                                        object
Street_Number                               int64
Street_Number_Suffix                       object
Street_Name                                object
Street_Suffix                              object
Unit                                      float64
Unit_Suffix                                object
Description                                object
Current_Status                             object
Current_Status_Date                        object
Filed_Date                                 object
Issued_Date                                object
Completed_Date                             object
First_Construction_Document_Date           object
Structural_Notification                    object
Number_of_Existing_Stories                float64
Number_of_Proposed_Stories                float64
Voluntary_Soft_Story_Retrofit              object
Fire_Only_Permit                           object
Permit_Expiration_Date                     object
Estimated_Cost                            float64
Revised_Cost                              float64
Existing_Use                               object
Existing_Units                            float64
Proposed_Use                               object
Proposed_Units                            float64
Plansets                                  float64
TIDF_Compliance                            object
Existing_Construction_Type                float64
Existing_Construction_Type_Description     object
Proposed_Construction_Type                float64
Proposed_Construction_Type_Description     object
Site_Permit                                object
Supervisor_District                       float64
Neighborhoods_Analysis_Boundaries          object
Zipcode                                   float64
Location                                   object
Record_ID                                   int64
dtype: object

In [13]:
#Veamos la cantidad de NAN en cada columna
databuild.isnull().sum()

Permit_Number                                  0
Permit_Type                                    0
Permit_Type_Definition                         0
Permit_Creation_Date                           0
Block                                          0
Lot                                            0
Street_Number                                  0
Street_Number_Suffix                      196684
Street_Name                                    0
Street_Suffix                               2768
Unit                                      169421
Unit_Suffix                               196939
Description                                  290
Current_Status                                 0
Current_Status_Date                            0
Filed_Date                                     0
Issued_Date                                14940
Completed_Date                            101709
First_Construction_Document_Date           14946
Structural_Notification                   191978
Number_of_Existing_Stories                 42784
Number_of_Proposed_Stories                 42868
Voluntary_Soft_Story_Retrofit             198865
Fire_Only_Permit                          180073
Permit_Expiration_Date                     51880
Estimated_Cost                             38066
Revised_Cost                                6066
Existing_Use                               41114
Existing_Units                             51538
Proposed_Use                               42439
Proposed_Units                             50911
Plansets                                   37309
TIDF_Compliance                           198898
Existing_Construction_Type                 43366
Existing_Construction_Type_Description     43366
Proposed_Construction_Type                 43162
Proposed_Construction_Type_Description     43162
Site_Permit                               193541
Supervisor_District                         1717
Neighborhoods_Analysis_Boundaries           1725
Zipcode                                     1716
Location                                    1700
Record_ID                                      0
dtype: int64

In [14]:
databuild.columns

Index(['Permit_Number', 'Permit_Type', 'Permit_Type_Definition',
       'Permit_Creation_Date', 'Block', 'Lot', 'Street_Number',
       'Street_Number_Suffix', 'Street_Name', 'Street_Suffix', 'Unit',
       'Unit_Suffix', 'Description', 'Current_Status', 'Current_Status_Date',
       'Filed_Date', 'Issued_Date', 'Completed_Date',
       'First_Construction_Document_Date', 'Structural_Notification',
       'Number_of_Existing_Stories', 'Number_of_Proposed_Stories',
       'Voluntary_Soft_Story_Retrofit', 'Fire_Only_Permit',
       'Permit_Expiration_Date', 'Estimated_Cost', 'Revised_Cost',
       'Existing_Use', 'Existing_Units', 'Proposed_Use', 'Proposed_Units',
       'Plansets', 'TIDF_Compliance', 'Existing_Construction_Type',
       'Existing_Construction_Type_Description', 'Proposed_Construction_Type',
       'Proposed_Construction_Type_Description', 'Site_Permit',
       'Supervisor_District', 'Neighborhoods_Analysis_Boundaries', 'Zipcode',
       'Location', 'Record_ID'],
      dtype='object')

In [15]:
#creamos un filtro de columnas que contengan datos de tipo fechas
filter_col = [col for col in databuild if ("Date" in col)]
filter_col

['Permit_Creation_Date',
 'Current_Status_Date',
 'Filed_Date',
 'Issued_Date',
 'Completed_Date',
 'First_Construction_Document_Date',
 'Permit_Expiration_Date']

In [16]:
#Verificamos que el filtro funciona
databuild[filter_col]

,Permit_Creation_Date,Current_Status_Date,Filed_Date,Issued_Date,Completed_Date,First_Construction_Document_Date,Permit_Expiration_Date
0,05/06/2015,12/21/2017,05/06/2015,11/09/2015,NaN,11/09/2015,11/03/2016
1,04/19/2016,08/03/2017,04/19/2016,08/03/2017,NaN,08/03/2017,12/03/2017
2,05/27/2016,09/26/2017,05/27/2016,NaN,NaN,NaN,NaN
3,11/07/2016,07/24/2017,11/07/2016,07/18/2017,07/24/2017,07/18/2017,07/13/2018
4,11/28/2016,12/01/2017,11/28/2016,12/01/2017,NaN,11/20/2017,12/01/2018
5,06/14/2017,07/06/2017,06/14/2017,07/06/2017,NaN,07/06/2017,07/01/2018
6,06/30/2017,07/12/2017,06/30/2017,06/30/2017,07/12/2017,06/30/2017,06/25/2018
7,06/30/2017,06/30/2017,06/30/2017,06/30/2017,NaN,06/30/2017,NaN
8,07/05/2017,07/05/2017,07/05/2017,07/05/2017,NaN,07/05/2017,NaN
9,07/06/2017,07/06/2017,07/06/2017,07/06/2017,NaN,07/06/2017,NaN
10,07/06/2017,07/06/2017,07/06/2017,07/06/2017,NaN,07/06/2017,NaN
11,07/07/2017,07/07/2017,07/07/2017,07/07/2017,NaN,07/07/2017,NaN
12,07/10/2017,07/10/2017,07/10/2017,07/10/2017,NaN,07/10/2017,NaN
13,07/25/2017,07/25/2017,07/25/2017,NaN,NaN,NaN,NaN
14,07/26/2017,07/26/2017,07/26/2017,07/26/2017,NaN,07/26/2017,NaN
15,07/27/2017,07/27/2017,07/27/2017,07/27/2017,NaN,07/27/2017,NaN
16,07/27/2017,07/27/2017,07/27/2017,07/27/2017,NaN,07/27/2017,NaN
17,07/27/2017,07/27/2017,07/27/2017,07/27/2017,NaN,07/27/2017,NaN
18,07/28/2017,07/28/2017,07/28/2017,NaN,NaN,NaN,NaN
19,07/28/2017,07/28/2017,07/28/2017,07/28/2017,NaN,07/28/2017,NaN
20,07/31/2017,07/31/2017,07/31/2017,07/31/2017,NaN,07/31/2017,NaN
21,08/01/2017,08/01/2017,08/01/2017,NaN,NaN,NaN,NaN
22,08/01/2017,08/01/2017,08/01/2017,NaN,NaN,NaN,NaN
23,08/07/2017,08/07/2017,08/07/2017,08/07/2017,NaN,08/07/2017,NaN
24,08/08/2017,08/08/2017,08/08/2017,08/08/2017,NaN,08/08/2017,08/08/2018
25,08/16/2017,08/16/2017,08/16/2017,08/16/2017,NaN,08/16/2017,02/16/2018
26,08/18/2017,08/18/2017,08/18/2017,08/18/2017,NaN,08/18/2017,NaN
27,08/21/2017,08/21/2017,08/21/2017,08/21/2017,NaN,08/21/2017,NaN
28,08/21/2017,08/21/2017,08/21/2017,08/21/2017,NaN,08/21/2017,NaN
29,08/22/2017,08/22/2017,08/22/2017,08/22/2017,NaN,08/22/2017,NaN
...,...,...,...,...,...,...,...
198870,02/23/2018,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN
198871,02/23/2018,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN
198872,02/23/2018,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN
198873,02/23/2018,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,06/23/2018
198874,02/23/2018,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,08/23/2018
198875,02/23/2018,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN
198876,02/23/2018,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN
198877,02/23/2018,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,06/23/2018
198878,02/23/2018,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN
198879,02/23/2018,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,08/23/2018
198880,02/23/2018,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN
198881,02/23/2018,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN
198882,02/23/2018,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,06/23/2018
198883,02/23/2018,02/23/2018,02/23/2018,02/23/2018,NaN,02/23/2018,NaN
198884,02/23/2018,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN
198885,02/23/2018,02/23/2018,02/23/2018,NaN,NaN,NaN,NaN
198886,09/06/2017,01/11/2018,09/06/2017,NaN,NaN,NaN,NaN
198887,10/04/2017,12/06/2017,10/04/2017,11/03/2017,12/06/2017,11/03/2017,11/03/2018
198888,10/11/2017,12/07/2017,10/11/2017,10/12/2017,12/07/2017,10/12/2017,10/12/2018
198889,10/24/2017,12/05/2017,10/24/2017,10/24/2017,12/05/2017,10/24/2017,04/24/2018
198890,11/27/2017,11/27/2017,11/27/2017,NaN,NaN,NaN,NaN
198891,11/27/2017,12/08/2017,11/27/2017,12/08/2017,NaN,12/08/2017,04/08/2018
198892,12/04/2017,01/16/2018,12/04/2017,01/16/2018,NaN,01/16/2018,01/16/2019
198893,12/05/2017,01/22/2018,12/05/2017,12/05/2017,01/22/2018,12/05/2017,04/05/2018
198894,12/05/2017,12/05/2017,12/05/2017,12/05/2017,NaN,12/05/2017,06/05/2018
198895,12/05/2017,12/05/2017,12/05/2017,12/05/2017,NaN,12/05/2017,NaN
198896,12/05/2017,12/06/2017,12/05/2017,12/06/2017,NaN,12/06/2017,04/06/2018
198897,12/06/2017,12/06/2017,12/06/2017,12/06/2017,NaN,12/06/2017,NaN
198898,12/06/2017,12/06/2017,12/06/2017,12/06/2017,NaN,12/06/2017,NaN
198899,12/07/2017,12/07/2017,12/07/2017,12/07/2017,NaN,12/07/2017,NaN

In [17]:
# Convertimos las columnas que contienen fechas a tipo datetime 
for col in filter_col:
 databuild[col] = pd.to_datetime(databuild[col],infer_datetime_format=True )

databuild[filter_col]

,Permit_Creation_Date,Current_Status_Date,Filed_Date,Issued_Date,Completed_Date,First_Construction_Document_Date,Permit_Expiration_Date
0,2015-05-06,2017-12-21,2015-05-06,2015-11-09,NaT,2015-11-09,2016-11-03
1,2016-04-19,2017-08-03,2016-04-19,2017-08-03,NaT,2017-08-03,2017-12-03
2,2016-05-27,2017-09-26,2016-05-27,NaT,NaT,NaT,NaT
3,2016-11-07,2017-07-24,2016-11-07,2017-07-18,2017-07-24,2017-07-18,2018-07-13
4,2016-11-28,2017-12-01,2016-11-28,2017-12-01,NaT,2017-11-20,2018-12-01
5,2017-06-14,2017-07-06,2017-06-14,2017-07-06,NaT,2017-07-06,2018-07-01
6,2017-06-30,2017-07-12,2017-06-30,2017-06-30,2017-07-12,2017-06-30,2018-06-25
7,2017-06-30,2017-06-30,2017-06-30,2017-06-30,NaT,2017-06-30,NaT
8,2017-07-05,2017-07-05,2017-07-05,2017-07-05,NaT,2017-07-05,NaT
9,2017-07-06,2017-07-06,2017-07-06,2017-07-06,NaT,2017-07-06,NaT
10,2017-07-06,2017-07-06,2017-07-06,2017-07-06,NaT,2017-07-06,NaT
11,2017-07-07,2017-07-07,2017-07-07,2017-07-07,NaT,2017-07-07,NaT
12,2017-07-10,2017-07-10,2017-07-10,2017-07-10,NaT,2017-07-10,NaT
13,2017-07-25,2017-07-25,2017-07-25,NaT,NaT,NaT,NaT
14,2017-07-26,2017-07-26,2017-07-26,2017-07-26,NaT,2017-07-26,NaT
15,2017-07-27,2017-07-27,2017-07-27,2017-07-27,NaT,2017-07-27,NaT
16,2017-07-27,2017-07-27,2017-07-27,2017-07-27,NaT,2017-07-27,NaT
17,2017-07-27,2017-07-27,2017-07-27,2017-07-27,NaT,2017-07-27,NaT
18,2017-07-28,2017-07-28,2017-07-28,NaT,NaT,NaT,NaT
19,2017-07-28,2017-07-28,2017-07-28,2017-07-28,NaT,2017-07-28,NaT
20,2017-07-31,2017-07-31,2017-07-31,2017-07-31,NaT,2017-07-31,NaT
21,2017-08-01,2017-08-01,2017-08-01,NaT,NaT,NaT,NaT
22,2017-08-01,2017-08-01,2017-08-01,NaT,NaT,NaT,NaT
23,2017-08-07,2017-08-07,2017-08-07,2017-08-07,NaT,2017-08-07,NaT
24,2017-08-08,2017-08-08,2017-08-08,2017-08-08,NaT,2017-08-08,2018-08-08
25,2017-08-16,2017-08-16,2017-08-16,2017-08-16,NaT,2017-08-16,2018-02-16
26,2017-08-18,2017-08-18,2017-08-18,2017-08-18,NaT,2017-08-18,NaT
27,2017-08-21,2017-08-21,2017-08-21,2017-08-21,NaT,2017-08-21,NaT
28,2017-08-21,2017-08-21,2017-08-21,2017-08-21,NaT,2017-08-21,NaT
29,2017-08-22,2017-08-22,2017-08-22,2017-08-22,NaT,2017-08-22,NaT
...,...,...,...,...,...,...,...
198870,2018-02-23,2018-02-23,2018-02-23,2018-02-23,NaT,2018-02-23,NaT
198871,2018-02-23,2018-02-23,2018-02-23,2018-02-23,NaT,2018-02-23,NaT
198872,2018-02-23,2018-02-23,2018-02-23,NaT,NaT,NaT,NaT
198873,2018-02-23,2018-02-23,2018-02-23,2018-02-23,NaT,2018-02-23,2018-06-23
198874,2018-02-23,2018-02-23,2018-02-23,2018-02-23,NaT,2018-02-23,2018-08-23
198875,2018-02-23,2018-02-23,2018-02-23,NaT,NaT,NaT,NaT
198876,2018-02-23,2018-02-23,2018-02-23,2018-02-23,NaT,2018-02-23,NaT
198877,2018-02-23,2018-02-23,2018-02-23,2018-02-23,NaT,2018-02-23,2018-06-23
198878,2018-02-23,2018-02-23,2018-02-23,NaT,NaT,NaT,NaT
198879,2018-02-23,2018-02-23,2018-02-23,2018-02-23,NaT,2018-02-23,2018-08-23
198880,2018-02-23,2018-02-23,2018-02-23,2018-02-23,NaT,2018-02-23,NaT
198881,2018-02-23,2018-02-23,2018-02-23,2018-02-23,NaT,2018-02-23,NaT
198882,2018-02-23,2018-02-23,2018-02-23,2018-02-23,NaT,2018-02-23,2018-06-23
198883,2018-02-23,2018-02-23,2018-02-23,2018-02-23,NaT,2018-02-23,NaT
198884,2018-02-23,2018-02-23,2018-02-23,NaT,NaT,NaT,NaT
198885,2018-02-23,2018-02-23,2018-02-23,NaT,NaT,NaT,NaT
198886,2017-09-06,2018-01-11,2017-09-06,NaT,NaT,NaT,NaT
198887,2017-10-04,2017-12-06,2017-10-04,2017-11-03,2017-12-06,2017-11-03,2018-11-03
198888,2017-10-11,2017-12-07,2017-10-11,2017-10-12,2017-12-07,2017-10-12,2018-10-12
198889,2017-10-24,2017-12-05,2017-10-24,2017-10-24,2017-12-05,2017-10-24,2018-04-24
198890,2017-11-27,2017-11-27,2017-11-27,NaT,NaT,NaT,NaT
198891,2017-11-27,2017-12-08,2017-11-27,2017-12-08,NaT,2017-12-08,2018-04-08
198892,2017-12-04,2018-01-16,2017-12-04,2018-01-16,NaT,2018-01-16,2019-01-16
198893,2017-12-05,2018-01-22,2017-12-05,2017-12-05,2018-01-22,2017-12-05,2018-04-05
198894,2017-12-05,2017-12-05,2017-12-05,2017-12-05,NaT,2017-12-05,2018-06-05
198895,2017-12-05,2017-12-05,2017-12-05,2017-12-05,NaT,2017-12-05,NaT
198896,2017-12-05,2017-12-06,2017-12-05,2017-12-06,NaT,2017-12-06,2018-04-06
198897,2017-12-06,2017-12-06,2017-12-06,2017-12-06,NaT,2017-12-06,NaT
198898,2017-12-06,2017-12-06,2017-12-06,2017-12-06,NaT,2017-12-06,NaT
198899,2017-12-07,2017-12-07,2017-12-07,2017-12-07,NaT,2017-12-07,NaT

In [18]:
#Vemos que los tipos de datos se cambiaron correctamente
databuild.dtypes

Permit_Number                                     object
Permit_Type                                        int64
Permit_Type_Definition                            object
Permit_Creation_Date                      datetime64[ns]
Block                                             object
Lot                                               object
Street_Number                                      int64
Street_Number_Suffix                              object
Street_Name                                       object
Street_Suffix                                     object
Unit                                             float64
Unit_Suffix                                       object
Description                                       object
Current_Status                                    object
Current_Status_Date                       datetime64[ns]
Filed_Date                                datetime64[ns]
Issued_Date                               datetime64[ns]
Completed_Date                            datetime64[ns]
First_Construction_Document_Date          datetime64[ns]
Structural_Notification                           object
Number_of_Existing_Stories                       float64
Number_of_Proposed_Stories                       float64
Voluntary_Soft_Story_Retrofit                     object
Fire_Only_Permit                                  object
Permit_Expiration_Date                    datetime64[ns]
Estimated_Cost                                   float64
Revised_Cost                                     float64
Existing_Use                                      object
Existing_Units                                   float64
Proposed_Use                                      object
Proposed_Units                                   float64
Plansets                                         float64
TIDF_Compliance                                   object
Existing_Construction_Type                       float64
Existing_Construction_Type_Description            object
Proposed_Construction_Type                       float64
Proposed_Construction_Type_Description            object
Site_Permit                                       object
Supervisor_District                              float64
Neighborhoods_Analysis_Boundaries                 object
Zipcode                                          float64
Location                                          object
Record_ID                                          int64
dtype: object

In [23]:
#Reordenamos la última columna "Record_ID" como la primera
databuild=databuild.set_index('Record_ID').reset_index()
databuild

,Record_ID,Permit_Number,Permit_Type,Permit_Type_Definition,Permit_Creation_Date,Block,Lot,Street_Number,Street_Number_Suffix,Street_Name,...,TIDF_Compliance,Existing_Construction_Type,Existing_Construction_Type_Description,Proposed_Construction_Type,Proposed_Construction_Type_Description,Site_Permit,Supervisor_District,Neighborhoods_Analysis_Boundaries,Zipcode,Location
0,1380611233945,201505065519,4,sign - erect,2015-05-06,0326,023,140,NaN,Ellis,...,NaN,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)"
1,1420164406718,201604195146,4,sign - erect,2016-04-19,0306,007,440,NaN,Geary,...,NaN,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)"
2,1424856504716,201605278609,3,additions alterations or repairs,2016-05-27,0595,203,1647,NaN,Pacific,...,NaN,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)"
3,1443574295566,201611072166,8,otc alterations permit,2016-11-07,0156,011,1230,NaN,Pacific,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)"
4,144548169992,201611283529,6,demolitions,2016-11-28,0342,001,950,NaN,Market,...,NaN,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)"
5,1466911170855,201706149344,8,otc alterations permit,2017-06-14,4105,009,800,NaN,Indiana,...,NaN,1.0,constr type 1,1.0,constr type 1,NaN,10.0,Potrero Hill,94107.0,"(37.75922331346539, -122.39170402628598)"
6,1468970403692,201706300814,8,otc alterations permit,2017-06-30,1739,020,1291,NaN,11th,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,5.0,Inner Sunset,94122.0,"(37.764145640138565, -122.46875112470363)"
7,1469035175050,M803667,8,otc alterations permit,2017-06-30,4789,014,1465,NaN,Revere,...,NaN,NaN,NaN,NaN,NaN,NaN,10.0,Bayview Hunters Point,94124.0,"(37.73005099023611, -122.38784938916618)"
8,1469198253772,M804227,8,otc alterations permit,2017-07-05,1212,054,2094,NaN,Fell,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.772393498502595, -122.45231466824669)"
9,146932394171,M804767,8,otc alterations permit,2017-07-06,1259,016,89,NaN,Alpine,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,Haight Ashbury,94117.0,"(37.7691724293766, -122.43734859051908)"
10,1469445246849,M805287,8,otc alterations permit,2017-07-06,3541,001,106,NaN,Sanchez,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,Castro/Upper Market,94114.0,"(37.767349757757145, -122.43140682973024)"
11,146961582526,M805907,8,otc alterations permit,2017-07-07,0829,021,675,NaN,Fell,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Hayes Valley,94102.0,"(37.774914087334544, -122.42886839796792)"
12,1469781206718,M806447,8,otc alterations permit,2017-07-10,6537,023,4082,NaN,25th,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,Noe Valley,94114.0,"(37.75006779619502, -122.43127350268124)"
13,1471799208305,201707252846,8,otc alterations permit,2017-07-25,6589,002R,681,NaN,27th,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,8.0,Noe Valley,94131.0,"(37.7462205625642, -122.4353484860549)"
14,147203988249,M813729,8,otc alterations permit,2017-07-26,1049,027,2761,NaN,Pine,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Pacific Heights,94115.0,"(37.78676200041077, -122.44124093333335)"
15,147208763456,M813907,8,otc alterations permit,2017-07-27,0243,043,840,NaN,Powell,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Chinatown,94108.0,"(37.7926690651263, -122.40883941791454)"
16,147211866168,M813967,8,otc alterations permit,2017-07-27,0268,008,220,NaN,Montgomery,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Financial District/South Beach,94104.0,"(37.79130641988351, -122.40198579459195)"
17,1472184412108,M814148,8,otc alterations permit,2017-07-27,3621,097,3707,NaN,21st,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,Noe Valley,94114.0,"(37.75607840165479, -122.43041143390109)"
18,1472277302360,201707283165,8,otc alterations permit,2017-07-28,0472,042,1307,NaN,Bay,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Marina,94123.0,"(37.8035183252307, -122.42863180996076)"
19,1472295408612,M814368,8,otc alterations permit,2017-07-28,2659,001,263,NaN,Corbett,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,Castro/Upper Market,94114.0,"(37.761092365437214, -122.44402154957145)"
20,1472619503582,M814967,8,otc alterations permit,2017-07-31,1176,068,1624,NaN,Fulton,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.77640228859421, -122.44361679686382)"
21,1472727381751,201708013476,8,otc alterations permit,2017-08-01,6529,010,3410,NaN,26th,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,9.0,Mission,94110.0,"(37.74914175355125, -122.41849211166853)"
22,147281357792,201708013544,3,additions alterations or repairs,2017-08-01,0074,043,2150,NaN,Taylor,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Russian Hill,94133.0,"(37.802405951667645, -122.41446286561653)"
23,147359384812,M816927,8,otc alterations permit,2017-08-07,0941,012,2824,NaN,Filbert,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Marina,94123.0,"(37.79697456740493, -122.44615769723546)"
24,1473796372030,201708084249,8,otc alterations permit,2017-08-08,0542,039,1,NaN,Charlton,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Marina,94123.0,"(37.79739093461306, -122.43127133823367)"
25,1474841115935,201708165014,8,otc alterations permit,2017-08-16,1824,006,1435,NaN,29th,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,4.0,Sunset/Parkside,94122.0,"(37.76052279949518, -122.4879889739165)"
26,1475223100163,M820728,8,otc alterations permit,2017-08-18,1449,006,331,NaN,17th,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Outer Richmond,94121.0,"(37.78177022745135, -122.47658979438802)"
27,147537591942,M821207,8,otc alterations permit,2017-08-21,1193,024,120,NaN,Shrader,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.77371007080848, -122.45243180846707)"
28,1475405117215,M821268,8,otc alterations permit,2017-08-21,1851,012,1512,NaN,06th,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,Inner Sunset,94122.0,"(37.760252335082875, -122.4625393396095)"
29,1475605447747,M821847,8,otc alterations permit,2017-08-22,0326,001,165,NaN,Powell,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78625524960107, -122.40834431815433)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198870,1498327347381,M893328,8,otc alterations permit,2018-02-23,0025,024,888,NaN,North Point,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Russian Hill,94109.0,"(37.8057495627139, -122.42181538597318)"
198871,1498328241068,M893347,8,otc alterations permit,2018-02-23,1253,001,701,NaN,Clayton,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Haight Ashbury,94117.0,"(37.76869660680249, -122.44864582118123)"
198872,1498329423799,201802232165,8,otc alterations permit,2018-02-23,3543,012,2123,NaN,Market,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,8.0,Castro/Upper Market,94114.0,"(37.76682151637876, -122.42926240167795)"
198873,1498330475722,201802232166,8,otc alterations permit,2018-02-23,5723,041,100,NaN,Tompkins,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,9.0,Bernal Heights,94110.0,"(37.73708421334594, -122.4157759256698)"
198874,1498331399024,201802232106,8,otc alterations permit,2018-02-23,6592,023,336,NaN,Duncan,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,8.0,Noe Valley,94131.0,"(37.746231746880696, -122.4285179313817)"
198875,149833282001,201802232167,8,otc alterations permit,2018-02-23,0807,010,580,NaN,Hayes,...,NaN,NaN,NaN,1.0,constr type 1,NaN,5.0,Hayes Valley,94102.0,"(37.776756688343944, -122.4260292019233)"
198876,149833392632,M893367,8,otc alterations permit,2018-02-23,1213,013,500,NaN,Stanyan,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.77277103274044, -122.45392960440346)"
198877,1498334221586,201802232169,8,otc alterations permit,2018-02-23,7103,020,91,NaN,Lobos,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,11.0,Oceanview/Merced/Ingleside,94112.0,"(37.7146765393289, -122.45557353560899)"
198878,1498335409431,201802232170,8,otc alterations permit,2018-02-23,3641,016,3134,NaN,24th,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,9.0,Mission,94110.0,"(37.752661001157854, -122.41485533400166)"
198879,1498336195616,201802232171,8,otc alterations permit,2018-02-23,6082,009,350,NaN,Paris,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,11.0,Excelsior,94112.0,"(37.72324934238285, -122.43409219261636)"
198880,1498337116842,M893387,8,otc alterations permit,2018-02-23,1841,025D,1442,NaN,Funston,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,Inner Sunset,94122.0,"(37.76117190796411, -122.47007880106999)"
198881,1498338347099,M893407,8,otc alterations permit,2018-02-23,0018,004,2300,NaN,Stockton,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,North Beach,94133.0,"(37.80747140583783, -122.41024025753224)"
198882,1498339194341,201802232172,8,otc alterations permit,2018-02-23,6021,001B,730,NaN,Excelsior,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,11.0,Excelsior,94112.0,"(37.723206757170836, -122.42763728105176)"
198883,149834069380,M893427,8,otc alterations permit,2018-02-23,0315,021,377,NaN,Geary,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78696971667916, -122.40936701144197)"
198884,1498341156230,M893447,8,otc alterations permit,2018-02-23,3504,030,1699,NaN,Market,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,Mission,94103.0,"(37.77217130976155, -122.42193576313322)"
198885,1498342127659,201802232173,8,otc alterations permit,2018-02-23,2150,001A,2007,NaN,30th,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,4.0,Sunset/Parkside,94116.0,"(37.74976582284573, -122.48824447038214)"
198886,1477559238559,201709066971,3,additions alterations or repairs,2017-09-06,0999,025,3191,NaN,Washington,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN
198887,1482126434174,201710040362,8,otc alterations permit,2017-10-04,0750,001,1521,NaN,Eddy,...,NaN,1.0,constr type 1,1.0,constr type 1,NaN,NaN,NaN,NaN,NaN
198888,1483035367814,201710110995,8,otc alterations permit,2017-10-11,0726,019,1410,NaN,Steiner,...,NaN,1.0,constr type 1,1.0,constr type 1,NaN,NaN,NaN,NaN,NaN
198889,1484587273155,201710242114,8,otc alterations permit,2017-10-24,1654,035,748,NaN,12th,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN
198890,1488352388160,201711274822,3,additions alterations or repairs,2017-11-27,3803,001,185,NaN,Berry,...,NaN,1.0,constr type 1,1.0,constr type 1,NaN,NaN,NaN,NaN,NaN
198891,148838081446,201711274844,8,otc alterations permit,2017-11-27,0766,008,590,NaN,Van Ness,...,NaN,3.0,constr type 3,3.0,constr type 3,NaN,NaN,NaN,NaN,NaN
198892,148916691540,201712045380,8,otc alterations permit,2017-12-04,1180,021,1543,NaN,Mcallister,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN
198893,1489281258414,201712055472,8,otc alterations permit,2017-12-05,1000,014,3018,NaN,Clay,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN
198894,1489308256860,201712055493,8,otc alterations permit,2017-12-05,3522,006,340,NaN,12th,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN
198895,1489337276729,M862628,8,otc alterations permit,2017-12-05,0113,017A,1228,NaN,Montgomery,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198896,1489462354993,201712055595,8,otc alterations permit,2017-12-05,0271,014,580,NaN,Bush,...,NaN,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN
198897,1489539379952,M863507,8,otc alterations permit,2017-12-06,4318,019,1568,NaN,Indiana,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198898,1489608233656,M863747,8,otc alterations permit,2017-12-06,0298,029,795,NaN,Sutter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198899,1489796283803,M864287,8,otc alterations permit,2017-12-07,0160,006,838,NaN,Pacific,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
#Verificamos que no haya filas repetidas
databuild.duplicated().sum()

0